### PR TITLE
Merge it please!  (Added Simplified Chinese Translation)

### PR DESCRIPTION
**Pull request by HofNature**

### CODE REVIEW

**Comment by Clayblockunova** [comment]
Hello!

I Didn't notice your PR, so I opened other PR for Simplified Chinese translation. Should I close mine?

Clayblockunova(Github)/Clayblock(Zhihu,Bilibili,MCBBS)

您好！

我当时没有注意到您这个PR，所以另开了一个同样针对简体中文翻译事宜的PR。需要我关闭那个PR吗？

Clayblockunova(Github)/Clayblock(知乎,B站,MCBBS)

**Comment by y2k04** [comment]
@Clayblockunova @HofNature Which one do you think is better in terms of the translation?

**Comment by HofNature** [comment]
Some of @Clayblockunova 's translations are a little strange.
Such as：
"解除对焦" -> "解除键盘锁定"
"解像度" -> "分辨率"
"虚拟机视频存储器" -> "虚拟显存"
I reviewed my translation and found that it also had some problems. I can't access my computer now, so I left comments in the file.

**Comment by HofNature** [comment]
> @Clayblockunova @HofNature Which one do you think is better in terms of the translation?

Some of @Clayblockunova 's translations are a little strange.
Such as：
"解除对焦" -> "解除键盘锁定"
"解像度" -> "分辨率"
"虚拟机视频存储器" -> "虚拟显存"
I reviewed my translation and found that it also had some problems. I can't access my computer now, so I left comments in the file.

**Comment by y2k04** [comment]
All good

**Pull request merged**
